{
 "title": "Dashboard_1",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Latency (p50, p95, p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_sum{}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущее количество запросов в обработке",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}