global:
  scrape_interval: 15s

scrape_configs:
  - job_name: events-service
    static_configs:
      - targets: ["events-api:8080"]
    metrics_path: /metrics

  - job_name: bookings-service
    static_configs:
      - targets: ["bookings-api:8080"]
    metrics_path: /metrics

  - job_name: users-service
    static_configs:
      - targets: ["users-api:8080"]
    metrics_path: /metrics